### PR TITLE
Phuntsok

### PR DESCRIPTION
**Pull request by phuntsoktseten**

### CODE REVIEW

**Comment by tungpatrick** [comment]
Hey Phuntsok! 

Could you please take a look at our repo and how it is organized before we merge this pull request. For some reason, you created another `test` folder in our cleanpy folder when we already had a test folder in the root of the project. I'm not entirely sure how that happened, but I think it's because you created a new file and forgot about the old one. Please remove the old unwanted files before we merge, otherwise we are merging files that we do not need. (Move your "new" test file to the original test folder.)

Also, is it possible that you could also delete your ".ipynb" file. We do not need ipynb files in the module. Thank you!

**Comment by phuntsoktseten** [comment]
OK, Patrick, I will take a look at our repo and make sure it's all organized. I will also look into the test folder and remove any unwanted files

**Comment by phuntsoktseten** [comment]
@tungpatrick. I removed the unwanted files and made sure our repo is in the right order. I also moved the new test to the original test folder. I also removed the ".ipynb" file.

**Comment by tungpatrick** [comment]
1. At the moment, your "column" argument only works when a list is inputted... For example, if I want to specify the 0th column (first column), i cannot say `column = 0`. I have to say `column = [0]`. I think you should make sure your function can deal with this. A quick fix could be like... if the person only put in a string or an integer, then make it a list of one element. Also, in your tests, I think you can write one test that actually checks whether or not your function would return an error when an incorrect "column" argument is passed in.
2. Go test out your code and see what happens when the user wants to `replace_na` on a column that is actually a categorical column (i.e. the values are strings). You cant find the mean or min or max of strings. So this would result in an error. You could catch these errors and return a more meaningful message by using `try...except...`. Also, you should test these sort of edge cases in your tests.

**Pull request merged**
